import { Injectable } from '@angular/core';

const mockData = [
  {
    customerNumber: '603840',
    customerId: 847121214,
    customerName: 'GALERIA S.à r.l. & Co. KG',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Dresden',
    parentCustomerNumber: '020758',
    orderId: 1102099,
    orderStatus: 'APPROVED',
    orderNumber: null,
    orderPieces: 218,
    salesPrice: 12583.82,
    planOrderValue: null,
    actualOrderValue: 5135.6,
    actualVsPlanPercentage: null,
    actualVsPlanAbsoluteDifference: null,
    currency: 'EUR',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2024110',
    brand: '6',
    country: 'DE',
    street: 'Prager Str. 12',
    zipCode: 'DE-01069',
    lastModifiedAt: '2024-07-31T11:33:32.54Z',
    lastModifiedBy: 'josef.tausch@de.street-one.com',
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 0.0,
    orderValueBudgetRelevant: 743.05,
    orderValueOnTop: 0.0,
    actualVsPreviousYearPercentage: null,
    actualVsPreviousYearAbsoluteDifference: 5135.6,
    menuSharePercentage: null,
    colorSharePercentage: null,
    designDepartmentSharePercentage: null,
    qrShare: 6088.76,
    qrSharePercentage: 48,
    rejectReason: null,
    campaignId: null,
    actions: ['VIEW', 'EXPORT', 'INSIGHTS'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'carolin.alfs',
    posTypeValue: '02',
  },
  {
    customerNumber: '603846',
    customerId: 847121217,
    customerName: 'GALERIA S.à r.l. & Co. KG',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Berlin',
    parentCustomerNumber: '020758',
    orderId: 1085579,
    orderStatus: 'APPROVED',
    orderNumber: null,
    orderPieces: 159,
    salesPrice: 8304.41,
    planOrderValue: null,
    actualOrderValue: 3388.8,
    actualVsPlanPercentage: null,
    actualVsPlanAbsoluteDifference: null,
    currency: 'EUR',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2024110',
    brand: '6',
    country: 'DE',
    street: 'Kurfürstendamm 231',
    zipCode: 'DE-10719',
    lastModifiedAt: '2024-07-31T11:33:32.54Z',
    lastModifiedBy: 'josef.tausch@de.street-one.com',
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 0.0,
    orderValueBudgetRelevant: 743.05,
    orderValueOnTop: 0.0,
    actualVsPreviousYearPercentage: null,
    actualVsPreviousYearAbsoluteDifference: 0,
    menuSharePercentage: null,
    colorSharePercentage: null,
    designDepartmentSharePercentage: null,
    qrShare: 6088.76,
    qrSharePercentage: 73,
    rejectReason: null,
    campaignId: null,
    actions: ['VIEW', 'EXPORT', 'INSIGHTS'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'carolin.alfs',
    posTypeValue: '02',
  },
  {
    customerNumber: '603847',
    customerId: 855728655,
    customerName: 'F. Klingenthal GmbH',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Saarbrücken',
    parentCustomerNumber: '020758',
    orderId: 1102101,
    orderStatus: 'SUBMITTED',
    orderNumber: null,
    orderPieces: 218,
    salesPrice: 12583.82,
    planOrderValue: null,
    actualOrderValue: 5135.6,
    actualVsPlanPercentage: null,
    actualVsPlanAbsoluteDifference: null,
    currency: 'USD',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2024110',
    brand: '6',
    country: 'DE',
    street: 'Bahnhofstr.',
    zipCode: 'DE-66111',
    lastModifiedAt: '2024-07-31T11:33:32.54Z',
    lastModifiedBy: 'josef.tausch@de.street-one.com',
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 0.0,
    orderValueBudgetRelevant: 743.05,
    orderValueOnTop: 0.0,
    actualVsPreviousYearPercentage: null,
    actualVsPreviousYearAbsoluteDifference: 5135.6,
    menuSharePercentage: null,
    colorSharePercentage: null,
    designDepartmentSharePercentage: null,
    qrShare: 6088.76,
    qrSharePercentage: 48,
    rejectReason: null,
    campaignId: null,
    actions: ['VIEW', 'EXPORT', 'INSIGHTS', 'APPROVE', 'REJECT'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'carolin.alfs',
    posTypeValue: '02',
  },
  {
    customerNumber: '603878',
    customerId: 855728652,
    customerName: 'Textilhäuser F. Klingenthal GmbH',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Hamburg',
    parentCustomerNumber: '020758',
    orderId: 1102187,
    orderStatus: 'OPEN',
    orderNumber: null,
    orderPieces: 290,
    salesPrice: 17731.1,
    planOrderValue: null,
    actualOrderValue: 7236.6,
    actualVsPlanPercentage: null,
    actualVsPlanAbsoluteDifference: null,
    currency: 'GBP',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2024110',
    brand: '6',
    country: 'DE',
    street: 'Mönckebergstr. 16',
    zipCode: 'DE-20095',
    lastModifiedAt: '2024-07-31T11:33:32.54Z',
    lastModifiedBy: 'josef.tausch@de.street-one.com',
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 0.0,
    orderValueBudgetRelevant: 743.05,
    orderValueOnTop: 0.0,
    actualVsPreviousYearPercentage: null,
    actualVsPreviousYearAbsoluteDifference: 7236.6,
    menuSharePercentage: null,
    colorSharePercentage: null,
    designDepartmentSharePercentage: null,
    qrShare: 6568.68,
    qrSharePercentage: 37,
    rejectReason: null,
    campaignId: null,
    actions: ['VIEW'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'carolin.alfs',
    posTypeValue: '02',
  },
  {
    customerNumber: '603913',
    customerId: 847121210,
    customerName: 'GALERIA S.à r.l. & Co. KG',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Berlin',
    parentCustomerNumber: '020758',
    orderId: 1097291,
    orderStatus: 'APPROVED',
    orderNumber: null,
    orderPieces: 218,
    salesPrice: 12583.82,
    planOrderValue: null,
    actualOrderValue: 5135.6,
    actualVsPlanPercentage: null,
    actualVsPlanAbsoluteDifference: null,
    currency: 'EUR',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2024110',
    brand: '6',
    country: 'DE',
    street: 'Hermannplatz',
    zipCode: 'DE-10967',
    lastModifiedAt: '2024-07-31T11:33:32.54Z',
    lastModifiedBy: 'josef.tausch@de.street-one.com',
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 0.0,
    orderValueBudgetRelevant: 743.05,
    orderValueOnTop: 0.0,
    actualVsPreviousYearPercentage: null,
    actualVsPreviousYearAbsoluteDifference: 5135.6,
    menuSharePercentage: null,
    colorSharePercentage: null,
    designDepartmentSharePercentage: null,
    qrShare: 6088.76,
    qrSharePercentage: 48,
    rejectReason: null,
    campaignId: null,
    actions: ['VIEW', 'EXPORT', 'INSIGHTS'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'carolin.alfs',
    posTypeValue: '02',
  },
  {
    customerNumber: '607716',
    customerId: 851810218,
    customerName: 'Magro',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Nürnberg',
    parentCustomerNumber: '020758',
    orderId: 1102351,
    orderStatus: 'NOT_CREATED_YET',
    orderNumber: null,
    orderPieces: 290,
    salesPrice: 17731.1,
    planOrderValue: null,
    actualOrderValue: 7236.6,
    actualVsPlanPercentage: null,
    actualVsPlanAbsoluteDifference: null,
    currency: 'EUR',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2024110',
    brand: '6',
    country: 'DE',
    street: 'Königstr. 14',
    zipCode: 'DE-90402',
    lastModifiedAt: '2024-07-31T11:33:32.543Z',
    lastModifiedBy: 'josef.tausch@de.street-one.com',
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 0.0,
    orderValueBudgetRelevant: 743.05,
    orderValueOnTop: 0.0,
    actualVsPreviousYearPercentage: null,
    actualVsPreviousYearAbsoluteDifference: -7236.6,
    menuSharePercentage: null,
    colorSharePercentage: null,
    designDepartmentSharePercentage: null,
    qrShare: 6568.68,
    qrSharePercentage: 37,
    rejectReason: null,
    campaignId: null,
    actions: ['VIEW', 'EXPORT', 'INSIGHTS', 'NEW_ORDER'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'carolin.alfs',
    posTypeValue: '02',
  },
  {
    customerNumber: '611131',
    customerId: 847121211,
    customerName: ' Jakob Jost GmbH',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Bochum',
    parentCustomerNumber: '020758',
    orderId: 1102197,
    orderStatus: 'APPROVED',
    orderNumber: null,
    orderPieces: 322,
    salesPrice: 19790.78,
    planOrderValue: null,
    actualOrderValue: 8077.15,
    actualVsPlanPercentage: null,
    actualVsPlanAbsoluteDifference: null,
    currency: 'EUR',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2024110',
    brand: '6',
    country: 'DE',
    street: 'Am Einkaufszentrum 38',
    zipCode: 'DE-44791',
    lastModifiedAt: '2024-07-31T11:33:32.543Z',
    lastModifiedBy: 'josef.tausch@de.street-one.com',
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 0.0,
    orderValueBudgetRelevant: 1110.25,
    orderValueOnTop: 0.0,
    actualVsPreviousYearPercentage: null,
    actualVsPreviousYearAbsoluteDifference: -8077.15,
    menuSharePercentage: null,
    colorSharePercentage: null,
    designDepartmentSharePercentage: null,
    qrShare: 8078.44,
    qrSharePercentage: 40,
    rejectReason: null,
    campaignId: null,
    actions: [],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'carolin.alfs',
    posTypeValue: '02',
  },
  {
    customerNumber: '612699',
    customerId: 855728651,
    customerName: 'GALERIA S.à r.l. & Co. KG',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Freiburg',
    parentCustomerNumber: '020758',
    orderId: 1097213,
    orderStatus: 'OPEN',
    orderNumber: null,
    orderPieces: 206,
    salesPrice: 11443.94,
    planOrderValue: null,
    actualOrderValue: 4670.3,
    actualVsPlanPercentage: null,
    actualVsPlanAbsoluteDifference: null,
    currency: 'EUR',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2024110',
    brand: '6',
    country: 'DE',
    street: 'Kaiser-Joseph-Str. 165',
    zipCode: 'DE-79098',
    lastModifiedAt: '2024-07-31T11:33:32.54Z',
    lastModifiedBy: 'josef.tausch@de.street-one.com',
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 0.0,
    orderValueBudgetRelevant: 743.05,
    orderValueOnTop: 0.0,
    actualVsPreviousYearPercentage: null,
    actualVsPreviousYearAbsoluteDifference: 4670.3,
    menuSharePercentage: null,
    colorSharePercentage: null,
    designDepartmentSharePercentage: null,
    qrShare: 6088.76,
    qrSharePercentage: 53,
    rejectReason: null,
    campaignId: null,
    actions: ['VIEW', 'EXPORT', 'INSIGHTS'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'carolin.alfs',
    posTypeValue: '02',
  },
  {
    customerNumber: '613120',
    customerId: 849579216,
    customerName: 'GALERIA S.à r.l. & Co. KG',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Karlsruhe',
    parentCustomerNumber: '020758',
    orderId: 1102199,
    orderStatus: 'APPROVED',
    orderNumber: null,
    orderPieces: 322,
    salesPrice: 19790.78,
    planOrderValue: null,
    actualOrderValue: 8077.15,
    actualVsPlanPercentage: null,
    actualVsPlanAbsoluteDifference: null,
    currency: 'EUR',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2024110',
    brand: '6',
    country: 'DE',
    street: 'Kaiserstr. 147-159',
    zipCode: 'DE-76133',
    lastModifiedAt: '2024-07-31T11:33:32.543Z',
    lastModifiedBy: 'josef.tausch@de.street-one.com',
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 0.0,
    orderValueBudgetRelevant: 1110.25,
    orderValueOnTop: 0.0,
    actualVsPreviousYearPercentage: 78,
    actualVsPreviousYearAbsoluteDifference: 8077.15,
    menuSharePercentage: null,
    colorSharePercentage: null,
    designDepartmentSharePercentage: null,
    qrShare: 8078.44,
    qrSharePercentage: 40,
    rejectReason: null,
    campaignId: null,
    actions: ['VIEW', 'EXPORT', 'INSIGHTS'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'carolin.alfs',
    posTypeValue: '02',
  },
  {
    customerNumber: '614653',
    customerId: 849579221,
    customerName: 'F. Klingenthal GmbH',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Köln',
    parentCustomerNumber: '020758',
    orderId: 1102189,
    orderStatus: 'REOPENED',
    orderNumber: null,
    orderPieces: 290,
    salesPrice: 17731.1,
    planOrderValue: null,
    actualOrderValue: 7236.6,
    actualVsPlanPercentage: null,
    actualVsPlanAbsoluteDifference: null,
    currency: 'USD',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2024110',
    brand: '6',
    country: 'DE',
    street: 'Breite Str. 103-135',
    zipCode: 'DE-50667',
    lastModifiedAt: '2024-07-31T11:33:32.54Z',
    lastModifiedBy: 'josef.tausch@de.street-one.com',
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 0.0,
    orderValueBudgetRelevant: 743.05,
    orderValueOnTop: 0.0,
    actualVsPreviousYearPercentage: null,
    actualVsPreviousYearAbsoluteDifference: 7236.6,
    menuSharePercentage: null,
    colorSharePercentage: null,
    designDepartmentSharePercentage: null,
    qrShare: 6568.68,
    qrSharePercentage: 37,
    rejectReason: null,
    campaignId: null,
    actions: ['VIEW', 'EXPORT', 'EDIT', 'EDIT_QEM_ORDER', 'INSIGHTS'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'carolin.alfs',
    posTypeValue: '02',
  },
  {
    customerNumber: '614656',
    customerId: 849579209,
    customerName: 'Textilhäuser F. Klingenthal GmbH',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Göttingen',
    parentCustomerNumber: '020758',
    orderId: 1097733,
    orderStatus: 'APPROVED',
    orderNumber: null,
    orderPieces: 236,
    salesPrice: 13843.64,
    planOrderValue: null,
    actualOrderValue: 5649.8,
    actualVsPlanPercentage: null,
    actualVsPlanAbsoluteDifference: null,
    currency: 'GBP',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2024110',
    brand: '6',
    country: 'DE',
    street: 'Groner Str. 43-47',
    zipCode: 'DE-37073',
    lastModifiedAt: '2024-07-31T11:33:32.54Z',
    lastModifiedBy: 'josef.tausch@de.street-one.com',
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 0.0,
    orderValueBudgetRelevant: 743.05,
    orderValueOnTop: 0.0,
    actualVsPreviousYearPercentage: null,
    actualVsPreviousYearAbsoluteDifference: 5649.8,
    menuSharePercentage: null,
    colorSharePercentage: null,
    designDepartmentSharePercentage: null,
    qrShare: 6088.76,
    qrSharePercentage: 44,
    rejectReason: null,
    campaignId: null,
    actions: ['VIEW', 'EXPORT', 'INSIGHTS'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'carolin.alfs',
    posTypeValue: '02',
  },
  {
    customerNumber: '614657',
    customerId: 847121213,
    customerName: 'GALERIA S.à r.l. & Co. KG',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Darmstadt',
    parentCustomerNumber: '020758',
    orderId: 1102103,
    orderStatus: 'APPROVED',
    orderNumber: null,
    orderPieces: 218,
    salesPrice: 12583.82,
    planOrderValue: null,
    actualOrderValue: 5135.6,
    actualVsPlanPercentage: null,
    actualVsPlanAbsoluteDifference: null,
    currency: 'EUR',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2024110',
    brand: '6',
    country: 'DE',
    street: 'Elisabethenstr. 15',
    zipCode: 'DE-64283',
    lastModifiedAt: '2024-07-31T11:33:32.54Z',
    lastModifiedBy: 'josef.tausch@de.street-one.com',
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 0.0,
    orderValueBudgetRelevant: 743.05,
    orderValueOnTop: 0.0,
    actualVsPreviousYearPercentage: null,
    actualVsPreviousYearAbsoluteDifference: 5135.6,
    menuSharePercentage: null,
    colorSharePercentage: null,
    designDepartmentSharePercentage: null,
    qrShare: 6088.76,
    qrSharePercentage: 48,
    rejectReason: null,
    campaignId: null,
    actions: ['VIEW', 'EXPORT', 'INSIGHTS'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'carolin.alfs',
    posTypeValue: '02',
  },
  {
    customerNumber: '614660',
    customerId: 849579208,
    customerName: 'GALERIA S.à r.l. & Co. KG',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Goslar',
    parentCustomerNumber: '020758',
    orderId: 1101955,
    orderStatus: 'OPEN',
    orderNumber: null,
    orderPieces: 159,
    salesPrice: 8304.41,
    planOrderValue: null,
    actualOrderValue: 3388.8,
    actualVsPlanPercentage: null,
    actualVsPlanAbsoluteDifference: null,
    currency: 'EUR',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2024110',
    brand: '6',
    country: 'DE',
    street: 'Rosentorstr. 1',
    zipCode: 'DE-38640',
    lastModifiedAt: '2024-07-31T11:33:32.54Z',
    lastModifiedBy: 'josef.tausch@de.street-one.com',
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 0.0,
    orderValueBudgetRelevant: 743.05,
    orderValueOnTop: 0.0,
    actualVsPreviousYearPercentage: 54,
    actualVsPreviousYearAbsoluteDifference: 3388.8,
    menuSharePercentage: null,
    colorSharePercentage: null,
    designDepartmentSharePercentage: null,
    qrShare: 6088.76,
    qrSharePercentage: 73,
    rejectReason: null,
    campaignId: null,
    actions: ['VIEW', 'EXPORT', 'INSIGHTS', 'EDIT_QEM_ORDER'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'carolin.alfs',
    posTypeValue: '02',
  },
  {
    customerNumber: '614672',
    customerId: 851810228,
    customerName: 'Magro',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Wiesbaden',
    parentCustomerNumber: '020758',
    orderId: 1102105,
    orderStatus: 'APPROVED',
    orderNumber: null,
    orderPieces: 218,
    salesPrice: 12583.82,
    planOrderValue: null,
    actualOrderValue: 5135.6,
    actualVsPlanPercentage: null,
    actualVsPlanAbsoluteDifference: null,
    currency: 'EUR',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2024110',
    brand: '6',
    country: 'DE',
    street: 'Kirchgasse 35-43',
    zipCode: 'DE-65183',
    lastModifiedAt: '2024-07-31T11:33:32.54Z',
    lastModifiedBy: 'josef.tausch@de.street-one.com',
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 0.0,
    orderValueBudgetRelevant: 743.05,
    orderValueOnTop: 0.0,
    actualVsPreviousYearPercentage: null,
    actualVsPreviousYearAbsoluteDifference: 5135.6,
    menuSharePercentage: null,
    colorSharePercentage: null,
    designDepartmentSharePercentage: null,
    qrShare: 6088.76,
    qrSharePercentage: 48,
    rejectReason: null,
    campaignId: null,
    actions: [],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'carolin.alfs',
    posTypeValue: '02',
  },
  {
    customerNumber: '614885',
    customerId: 849579204,
    customerName: 'GALERIA S.à r.l. & Co. KG',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Erfurt',
    parentCustomerNumber: '020758',
    orderId: 1102001,
    orderStatus: 'APPROVED',
    orderNumber: null,
    orderPieces: 206,
    salesPrice: 11443.94,
    planOrderValue: null,
    actualOrderValue: 4670.3,
    actualVsPlanPercentage: null,
    actualVsPlanAbsoluteDifference: null,
    currency: 'EUR',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2024110',
    brand: '6',
    country: 'DE',
    street: 'Anger 1-3',
    zipCode: 'DE-99084',
    lastModifiedAt: '2024-07-31T11:33:32.54Z',
    lastModifiedBy: 'josef.tausch@de.street-one.com',
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 0.0,
    orderValueBudgetRelevant: 743.05,
    orderValueOnTop: 0.0,
    actualVsPreviousYearPercentage: null,
    actualVsPreviousYearAbsoluteDifference: 4670.3,
    menuSharePercentage: null,
    colorSharePercentage: null,
    designDepartmentSharePercentage: null,
    qrShare: 6088.76,
    qrSharePercentage: 53,
    rejectReason: null,
    campaignId: null,
    actions: ['VIEW', 'EXPORT', 'INSIGHTS'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'carolin.alfs',
    posTypeValue: '02',
  },
  {
    customerNumber: '616107',
    customerId: 849579224,
    customerName: 'F. Klingenthal GmbH',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Lörrach',
    parentCustomerNumber: '020758',
    orderId: 1101957,
    orderStatus: 'APPROVED',
    orderNumber: null,
    orderPieces: 159,
    salesPrice: 8304.41,
    planOrderValue: null,
    actualOrderValue: 3388.8,
    actualVsPlanPercentage: null,
    actualVsPlanAbsoluteDifference: null,
    currency: 'USD',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2024110',
    brand: '6',
    country: 'DE',
    street: 'Turmstr. 1',
    zipCode: 'DE-79539',
    lastModifiedAt: '2024-07-31T11:33:32.54Z',
    lastModifiedBy: 'josef.tausch@de.street-one.com',
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 0.0,
    orderValueBudgetRelevant: 743.05,
    orderValueOnTop: 0.0,
    actualVsPreviousYearPercentage: -22.5,
    actualVsPreviousYearAbsoluteDifference: 3388.8,
    menuSharePercentage: null,
    colorSharePercentage: null,
    designDepartmentSharePercentage: null,
    qrShare: 6088.76,
    qrSharePercentage: 73,
    rejectReason: null,
    campaignId: null,
    actions: ['VIEW', 'EXPORT', 'INSIGHTS'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'carolin.alfs',
    posTypeValue: '02',
  },
  {
    customerNumber: '411094',
    customerId: 515882546,
    customerName: 'Magro',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Bückeburg',
    parentCustomerNumber: '020476',
    orderId: 1068889,
    orderStatus: 'APPROVED',
    orderNumber: null,
    orderPieces: 58,
    salesPrice: 2879.42,
    planOrderValue: 1238.8,
    actualOrderValue: 1175.0,
    actualVsPlanPercentage: -5.150145301905063,
    actualVsPlanAbsoluteDifference: -63.799999999999955,
    currency: 'EUR',
    orderType: 'EPROM_MENU_ORDER',
    collection: '2024100',
    brand: '4',
    country: 'DE',
    street: 'Lange Str. 70-72',
    zipCode: 'DE-31675',
    lastModifiedAt: '2024-06-27T16:16:00.977Z',
    lastModifiedBy: 'tim.dieckmann@de.street-one.com',
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 1542.3,
    orderValueBudgetRelevant: 783.5999999999999,
    orderValueOnTop: 0.0,
    actualVsPreviousYearPercentage: -23.81508137197692,
    actualVsPreviousYearAbsoluteDifference: -367.29999999999995,
    menuSharePercentage: 22.916666666666668,
    colorSharePercentage: 27.083125000000003,
    designDepartmentSharePercentage: 50.0,
    qrShare: 0.0,
    qrSharePercentage: 0,
    rejectReason: null,
    campaignId: null,
    actions: ['VIEW', 'EXPORT', 'INSIGHTS', 'EDIT_QEM_ORDER'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'tim.dieckmann',
    posTypeValue: '02',
  },
  {
    customerNumber: '419603',
    customerId: 515882544,
    customerName: 'Magro',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Marklohe',
    parentCustomerNumber: '020476',
    orderId: 1071767,
    orderStatus: 'APPROVED',
    orderNumber: null,
    orderPieces: 58,
    salesPrice: 2879.42,
    planOrderValue: 1188.8,
    actualOrderValue: 1175.0,
    actualVsPlanPercentage: -1.1608344549125182,
    actualVsPlanAbsoluteDifference: -13.799999999999955,
    currency: 'GBP',
    orderType: 'EPROM_MENU_ORDER',
    collection: '2024100',
    brand: '4',
    country: 'DE',
    street: 'Rathausstr. 1',
    zipCode: 'DE-31608',
    lastModifiedAt: '2024-06-27T16:16:09.56Z',
    lastModifiedBy: 'tim.dieckmann@de.street-one.com',
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 1542.3,
    orderValueBudgetRelevant: 783.5999999999999,
    orderValueOnTop: 0.0,
    actualVsPreviousYearPercentage: -23.81508137197692,
    actualVsPreviousYearAbsoluteDifference: -367.29999999999995,
    menuSharePercentage: 22.916666666666668,
    colorSharePercentage: 27.083125000000003,
    designDepartmentSharePercentage: 50.0,
    qrShare: 0.0,
    qrSharePercentage: 0,
    rejectReason: null,
    campaignId: null,
    actions: ['VIEW', 'EXPORT', 'INSIGHTS'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'vincent.fraenzle',
    posTypeValue: '02',
  },
  {
    customerNumber: '431013',
    customerId: 515882541,
    customerName: 'Magro',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Wagenfeld',
    parentCustomerNumber: '020476',
    orderId: 1071769,
    orderStatus: 'APPROVED',
    orderNumber: null,
    orderPieces: 58,
    salesPrice: 2879.42,
    planOrderValue: 1174.8,
    actualOrderValue: 1175.0,
    actualVsPlanPercentage: 0.01702417432754011,
    actualVsPlanAbsoluteDifference: 0.20000000000004547,
    currency: 'EUR',
    orderType: 'EPROM_MENU_ORDER',
    collection: '2024100',
    brand: '4',
    country: 'DE',
    street: 'Mindener Str. 2',
    zipCode: 'DE-49419',
    lastModifiedAt: '2024-06-27T16:16:18.313Z',
    lastModifiedBy: 'tim.dieckmann@de.street-one.com',
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 1542.3,
    orderValueBudgetRelevant: 783.5999999999999,
    orderValueOnTop: 0.0,
    actualVsPreviousYearPercentage: -23.81508137197692,
    actualVsPreviousYearAbsoluteDifference: -367.29999999999995,
    menuSharePercentage: 22.916666666666668,
    colorSharePercentage: 27.083125000000003,
    designDepartmentSharePercentage: 50.0,
    qrShare: 0.0,
    qrSharePercentage: 0,
    rejectReason: null,
    campaignId: null,
    actions: ['VIEW', 'EXPORT', 'INSIGHTS'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'michael.reid',
    posTypeValue: '02',
  },
  {
    customerNumber: '451906',
    customerId: 515882547,
    customerName: 'Magro',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Bohmte',
    parentCustomerNumber: '020476',
    orderId: 1071771,
    orderStatus: 'APPROVED',
    orderNumber: null,
    orderPieces: 58,
    salesPrice: 2879.42,
    planOrderValue: 1174.8,
    actualOrderValue: 1175.0,
    actualVsPlanPercentage: 0.01702417432754011,
    actualVsPlanAbsoluteDifference: 0.20000000000004547,
    currency: 'EUR',
    orderType: 'EPROM_MENU_ORDER',
    collection: '2024100',
    brand: '4',
    country: 'DE',
    street: 'Schützenstr. 1',
    zipCode: 'DE-49163',
    lastModifiedAt: '2024-06-27T16:16:28.553Z',
    lastModifiedBy: 'tim.dieckmann@de.street-one.com',
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 1542.3,
    orderValueBudgetRelevant: 783.5999999999999,
    orderValueOnTop: 0.0,
    actualVsPreviousYearPercentage: -23.81508137197692,
    actualVsPreviousYearAbsoluteDifference: 0,
    menuSharePercentage: 22.916666666666668,
    colorSharePercentage: 27.083125000000003,
    designDepartmentSharePercentage: 50.0,
    qrShare: 0.0,
    qrSharePercentage: 0,
    rejectReason: null,
    campaignId: null,
    actions: ['VIEW', 'EXPORT', 'INSIGHTS'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'michael.reid',
    posTypeValue: '02',
  },
  {
    customerNumber: '203141',
    customerId: 25164,
    customerName: ' Jakob Jost GmbH',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Braunschweig',
    parentCustomerNumber: '020758',
    orderId: 1096991,
    orderStatus: 'APPROVED',
    orderNumber: null,
    orderPieces: 64,
    salesPrice: 3999.36,
    planOrderValue: 3572.56,
    actualOrderValue: 1632.4,
    actualVsPlanPercentage: -54.30727545513581,
    actualVsPlanAbsoluteDifference: -1940.1599999999999,
    currency: 'EUR',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2024110',
    brand: '2',
    country: 'DE',
    street: 'Schuhstr. 29-34',
    zipCode: 'DE-38100',
    lastModifiedAt: '2024-07-31T12:40:57.263Z',
    lastModifiedBy: 'sonia.hutner@cecil.de',
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 5581.56,
    orderValueBudgetRelevant: 4114.32,
    orderValueOnTop: 5381.219999999999,
    actualVsPreviousYearPercentage: -70.7536960992984,
    actualVsPreviousYearAbsoluteDifference: -3949.1600000000003,
    menuSharePercentage: null,
    colorSharePercentage: 37.42578947368421,
    designDepartmentSharePercentage: 48.332,
    qrShare: 3199.52,
    qrSharePercentage: 80,
    rejectReason: null,
    campaignId: null,
    actions: ['VIEW', 'EXPORT', 'INSIGHTS'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'carolin.alfs',
    posTypeValue: '02',
  },
  {
    customerNumber: '203371',
    customerId: 25150,
    customerName: 'GALERIA S.à r.l. & Co. KG',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Düsseldorf',
    parentCustomerNumber: '020758',
    orderId: 1104351,
    orderStatus: 'SUBMITTED',
    orderNumber: null,
    orderPieces: 128,
    salesPrice: 7236.72,
    planOrderValue: 3296.0,
    actualOrderValue: 2953.82,
    actualVsPlanPercentage: -10.381674757281544,
    actualVsPlanAbsoluteDifference: -342.17999999999984,
    currency: 'GBP',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2024110',
    brand: '2',
    country: 'DE',
    street: 'Schadowstr. 93',
    zipCode: 'DE-40212',
    lastModifiedAt: '2024-07-31T12:41:13.87Z',
    lastModifiedBy: 'sonia.hutner@cecil.de',
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 3062.17,
    orderValueBudgetRelevant: 0.0,
    orderValueOnTop: 0.0,
    actualVsPreviousYearPercentage: -3.5383404579105604,
    actualVsPreviousYearAbsoluteDifference: -108.34999999999991,
    menuSharePercentage: null,
    colorSharePercentage: 88.472,
    designDepartmentSharePercentage: 85.41666666666667,
    qrShare: 4969.2,
    qrSharePercentage: 68,
    rejectReason: null,
    campaignId: null,
    actions: ['VIEW', 'EXPORT', 'INSIGHTS', 'APPROVE', 'REJECT'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'carolin.alfs',
    posTypeValue: '02',
  },
  {
    customerNumber: '203839',
    customerId: 25266,
    customerName: 'Textilhäuser F. Klingenthal GmbH',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Dortmund',
    parentCustomerNumber: '020758',
    orderId: 1103043,
    orderStatus: 'APPROVED',
    orderNumber: null,
    orderPieces: 64,
    salesPrice: 3999.36,
    planOrderValue: 3775.69,
    actualOrderValue: 1632.4,
    actualVsPlanPercentage: -56.76551835558534,
    actualVsPlanAbsoluteDifference: -2143.29,
    currency: 'USD',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2024110',
    brand: '2',
    country: 'DE',
    street: 'Westenhellweg 30-36',
    zipCode: 'DE-44137',
    lastModifiedAt: '2024-07-31T12:41:02.88Z',
    lastModifiedBy: 'sonia.hutner@cecil.de',
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 8162.76,
    orderValueBudgetRelevant: 8448.93,
    orderValueOnTop: 5893.2300000000005,
    actualVsPreviousYearPercentage: -80.00186211526493,
    actualVsPreviousYearAbsoluteDifference: -6530.360000000001,
    menuSharePercentage: null,
    colorSharePercentage: 37.42578947368421,
    designDepartmentSharePercentage: 48.332,
    qrShare: 3199.52,
    qrSharePercentage: 80,
    rejectReason: null,
    campaignId: null,
    actions: ['VIEW', 'EXPORT', 'INSIGHTS'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'carolin.alfs',
    posTypeValue: '02',
  },
  {
    customerNumber: '203840',
    customerId: 25265,
    customerName: 'GALERIA S.à r.l. & Co. KG',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Dresden',
    parentCustomerNumber: '020758',
    orderId: 1103165,
    orderStatus: 'APPROVED',
    orderNumber: null,
    orderPieces: 103,
    salesPrice: 6168.97,
    planOrderValue: 4396.56,
    actualOrderValue: 2517.99,
    actualVsPlanPercentage: -42.72817839401715,
    actualVsPlanAbsoluteDifference: -1878.5700000000006,
    currency: 'EUR',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2024110',
    brand: '2',
    country: 'DE',
    street: 'Prager Str. 12',
    zipCode: 'DE-01069',
    lastModifiedAt: '2024-07-31T12:41:08.24Z',
    lastModifiedBy: 'sonia.hutner@cecil.de',
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 8134.46,
    orderValueBudgetRelevant: 4114.32,
    orderValueOnTop: 5381.219999999999,
    actualVsPreviousYearPercentage: -69.04539453141328,
    actualVsPreviousYearAbsoluteDifference: -5616.47,
    menuSharePercentage: null,
    colorSharePercentage: 71.63684210526317,
    designDepartmentSharePercentage: 64.672,
    qrShare: 4249.37,
    qrSharePercentage: 68,
    rejectReason: null,
    campaignId: null,
    actions: ['VIEW', 'EXPORT', 'INSIGHTS'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'carolin.alfs',
    posTypeValue: '02',
  },
  {
    customerNumber: '203841',
    customerId: 25255,
    customerName: 'GALERIA S.à r.l. & Co. KG',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Kiel',
    parentCustomerNumber: '020758',
    orderId: 1103167,
    orderStatus: 'APPROVED',
    orderNumber: null,
    orderPieces: 103,
    salesPrice: 6168.97,
    planOrderValue: 4572.32,
    actualOrderValue: 2517.99,
    actualVsPlanPercentage: -44.92970745704588,
    actualVsPlanAbsoluteDifference: -2054.33,
    currency: 'EUR',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2024110',
    brand: '2',
    country: 'DE',
    street: 'Sophienblatt 2',
    zipCode: 'DE-24103',
    lastModifiedAt: '2024-07-31T12:41:08.24Z',
    lastModifiedBy: 'sonia.hutner@cecil.de',
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 5057.56,
    orderValueBudgetRelevant: 2351.04,
    orderValueOnTop: 5220.57,
    actualVsPreviousYearPercentage: -50.213343984055555,
    actualVsPreviousYearAbsoluteDifference: -2539.5700000000006,
    menuSharePercentage: null,
    colorSharePercentage: 63.11857142857143,
    designDepartmentSharePercentage: 61.194,
    qrShare: 4249.37,
    qrSharePercentage: 68,
    rejectReason: null,
    campaignId: null,
    actions: ['VIEW', 'EXPORT', 'INSIGHTS'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'carolin.alfs',
    posTypeValue: '02',
  },
  {
    customerNumber: '203846',
    customerId: 25297,
    customerName: 'Magro',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Berlin',
    parentCustomerNumber: '020758',
    orderId: 1103169,
    orderStatus: 'APPROVED',
    orderNumber: null,
    orderPieces: 103,
    salesPrice: 6168.97,
    planOrderValue: 2472.0,
    actualOrderValue: 2517.99,
    actualVsPlanPercentage: 1.8604368932038762,
    actualVsPlanAbsoluteDifference: 45.98999999999978,
    currency: 'GBP',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2024110',
    brand: '2',
    country: 'DE',
    street: 'Kurfürstendamm 231',
    zipCode: 'DE-10719',
    lastModifiedAt: '2024-07-31T12:41:08.24Z',
    lastModifiedBy: 'sonia.hutner@cecil.de',
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 2416.62,
    orderValueBudgetRelevant: 0.0,
    orderValueOnTop: 0.0,
    actualVsPreviousYearPercentage: 4.194701690791258,
    actualVsPreviousYearAbsoluteDifference: 0,
    menuSharePercentage: null,
    colorSharePercentage: 66.333,
    designDepartmentSharePercentage: 87.5,
    qrShare: 4249.37,
    qrSharePercentage: 68,
    rejectReason: null,
    campaignId: null,
    actions: ['VIEW', 'EXPORT', 'INSIGHTS'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'carolin.alfs',
    posTypeValue: '02',
  },
  {
    customerNumber: '203847',
    customerId: 25364,
    customerName: 'GALERIA S.à r.l. & Co. KG',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Saarbrücken',
    parentCustomerNumber: '020758',
    orderId: 1103045,
    orderStatus: 'NOT_CREATED_YET',
    orderNumber: null,
    orderPieces: 64,
    salesPrice: 3999.36,
    planOrderValue: 3748.32,
    actualOrderValue: 1632.4,
    actualVsPlanPercentage: -56.44982285397191,
    actualVsPlanAbsoluteDifference: -2115.92,
    currency: 'GBP',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2024110',
    brand: '2',
    country: 'DE',
    street: 'Bahnhofstr. 15',
    zipCode: 'DE-66111',
    lastModifiedAt: '2024-07-31T12:41:02.88Z',
    lastModifiedBy: 'sonia.hutner@cecil.de',
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 3935.5299999999997,
    orderValueBudgetRelevant: 2351.04,
    orderValueOnTop: 5220.57,
    actualVsPreviousYearPercentage: -58.52146978932951,
    actualVsPreviousYearAbsoluteDifference: -2303.1299999999997,
    menuSharePercentage: null,
    colorSharePercentage: 37.42578947368421,
    designDepartmentSharePercentage: 48.332,
    qrShare: 3199.52,
    qrSharePercentage: 80,
    rejectReason: null,
    campaignId: null,
    actions: ['START_QEM_ORDER'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'carolin.alfs',
    posTypeValue: '02',
  },
  {
    customerNumber: '203848',
    customerId: 25196,
    customerName: 'F. Klingenthal GmbH',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Offenburg',
    parentCustomerNumber: '020758',
    orderId: 1102955,
    orderStatus: 'APPROVED',
    orderNumber: null,
    orderPieces: 49,
    salesPrice: 3059.51,
    planOrderValue: 3336.32,
    actualOrderValue: 1248.79,
    actualVsPlanPercentage: -62.569837425666606,
    actualVsPlanAbsoluteDifference: -2087.53,
    currency: 'USD',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2024110',
    brand: '2',
    country: 'DE',
    street: 'Lindenplatz 3',
    zipCode: 'DE-77652',
    lastModifiedAt: '2024-07-31T12:41:02.88Z',
    lastModifiedBy: 'sonia.hutner@cecil.de',
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 3935.5299999999997,
    orderValueBudgetRelevant: 2351.04,
    orderValueOnTop: 5220.57,
    actualVsPreviousYearPercentage: -68.26882275068415,
    actualVsPreviousYearAbsoluteDifference: -2686.74,
    menuSharePercentage: null,
    colorSharePercentage: 31.666666666666668,
    designDepartmentSharePercentage: 45.69222222222223,
    qrShare: 2399.64,
    qrSharePercentage: 78,
    rejectReason: null,
    campaignId: null,
    actions: ['VIEW', 'EXPORT', 'INSIGHTS'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'carolin.alfs',
    posTypeValue: '02',
  },
  {
    customerNumber: '203849',
    customerId: 25200,
    customerName: ' Jakob Jost GmbH',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Gießen',
    parentCustomerNumber: '020758',
    orderId: 1102907,
    orderStatus: 'SUBMITTED',
    orderNumber: null,
    orderPieces: 37,
    salesPrice: 2279.63,
    planOrderValue: 2951.69,
    actualOrderValue: 930.49,
    actualVsPlanPercentage: -68.47602559889418,
    actualVsPlanAbsoluteDifference: -2021.2,
    currency: 'EUR',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2024110',
    brand: '2',
    country: 'DE',
    street: 'Seltersweg 64',
    zipCode: 'DE-35390',
    lastModifiedAt: '2024-07-31T12:40:57.263Z',
    lastModifiedBy: 'sonia.hutner@cecil.de',
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 7126.54,
    orderValueBudgetRelevant: 8448.93,
    orderValueOnTop: 5893.23,
    actualVsPreviousYearPercentage: -86.94331330491374,
    actualVsPreviousYearAbsoluteDifference: -6196.05,
    menuSharePercentage: null,
    colorSharePercentage: 25.0,
    designDepartmentSharePercentage: 42.13666666666667,
    qrShare: 1619.76,
    qrSharePercentage: 71,
    rejectReason: null,
    campaignId: null,
    actions: ['VIEW', 'EXPORT', 'INSIGHTS', 'APPROVE', 'REJECT'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'carolin.alfs',
    posTypeValue: '02',
  },
  {
    customerNumber: '203878',
    customerId: 25351,
    customerName: 'Magro',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Hamburg',
    parentCustomerNumber: '020758',
    orderId: 1103171,
    orderStatus: 'APPROVED',
    orderNumber: null,
    orderPieces: 103,
    salesPrice: 6168.97,
    planOrderValue: 4599.69,
    actualOrderValue: 2517.99,
    actualVsPlanPercentage: -45.257397781154815,
    actualVsPlanAbsoluteDifference: -2081.7,
    currency: 'EUR',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2024110',
    brand: '2',
    country: 'DE',
    street: 'Mönckebergstr. 16',
    zipCode: 'DE-20095',
    lastModifiedAt: '2024-07-31T12:41:08.24Z',
    lastModifiedBy: 'sonia.hutner@cecil.de',
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 7655.4400000000005,
    orderValueBudgetRelevant: 8448.93,
    orderValueOnTop: 5893.2300000000005,
    actualVsPreviousYearPercentage: -67.10848755917361,
    actualVsPreviousYearAbsoluteDifference: -5137.450000000001,
    menuSharePercentage: null,
    colorSharePercentage: 63.11857142857143,
    designDepartmentSharePercentage: 61.194,
    qrShare: 4249.37,
    qrSharePercentage: 68,
    rejectReason: null,
    campaignId: null,
    actions: ['VIEW', 'EXPORT', 'INSIGHTS', 'EDIT', 'EDIT_QEM_ORDER'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'carolin.alfs',
    posTypeValue: '02',
  },
  {
    customerNumber: '203913',
    customerId: 25268,
    customerName: 'Textilhäuser F. Klingenthal GmbH',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Berlin',
    parentCustomerNumber: '020758',
    orderId: 1103173,
    orderStatus: 'APPROVED',
    orderNumber: null,
    orderPieces: 103,
    salesPrice: 6168.97,
    planOrderValue: 2884.0,
    actualOrderValue: 2517.99,
    actualVsPlanPercentage: -12.691054091539533,
    actualVsPlanAbsoluteDifference: -366.0100000000002,
    currency: 'EUR',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2024110',
    brand: '2',
    country: 'DE',
    street: 'Hermannplatz',
    zipCode: 'DE-10967',
    lastModifiedAt: '2024-07-31T12:41:08.24Z',
    lastModifiedBy: 'sonia.hutner@cecil.de',
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 2917.7200000000003,
    orderValueBudgetRelevant: 0.0,
    orderValueOnTop: 0.0,
    actualVsPreviousYearPercentage: -13.700080885074662,
    actualVsPreviousYearAbsoluteDifference: -399.7300000000005,
    menuSharePercentage: null,
    colorSharePercentage: 75.55533333333334,
    designDepartmentSharePercentage: 72.22222222222223,
    qrShare: 4249.37,
    qrSharePercentage: 68,
    rejectReason: null,
    campaignId: null,
    actions: ['VIEW', 'EXPORT', 'INSIGHTS'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'carolin.alfs',
    posTypeValue: '02',
  },
  {
    customerNumber: '203914',
    customerId: 25269,
    customerName: ' Jakob Jost GmbH',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Landshut',
    parentCustomerNumber: '020758',
    orderId: 1102957,
    orderStatus: 'APPROVED',
    orderNumber: null,
    orderPieces: 49,
    salesPrice: 3059.51,
    planOrderValue: 3336.32,
    actualOrderValue: 1248.79,
    actualVsPlanPercentage: -62.569837425666606,
    actualVsPlanAbsoluteDifference: -2087.53,
    currency: 'EUR',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2024110',
    brand: '2',
    country: 'DE',
    street: 'Ländtorplatz 1',
    zipCode: 'DE-84028',
    lastModifiedAt: '2024-07-31T12:41:02.88Z',
    lastModifiedBy: 'sonia.hutner@cecil.de',
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 3935.5299999999997,
    orderValueBudgetRelevant: 2351.04,
    orderValueOnTop: 5220.57,
    actualVsPreviousYearPercentage: -68.26882275068415,
    actualVsPreviousYearAbsoluteDifference: -2686.74,
    menuSharePercentage: null,
    colorSharePercentage: 31.666666666666668,
    designDepartmentSharePercentage: 45.69222222222223,
    qrShare: 2399.64,
    qrSharePercentage: 78,
    rejectReason: null,
    campaignId: null,
    actions: ['VIEW', 'EXPORT', 'INSIGHTS'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'carolin.alfs',
    posTypeValue: '02',
  },
  {
    customerNumber: '204887',
    customerId: 25380,
    customerName: 'F. Klingenthal GmbH',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Münster',
    parentCustomerNumber: '020758',
    orderId: 1096823,
    orderStatus: 'NOT_CREATED_YET',
    orderNumber: null,
    orderPieces: 49,
    salesPrice: 3059.51,
    planOrderValue: 3160.56,
    actualOrderValue: 1248.79,
    actualVsPlanPercentage: -60.48833118181588,
    actualVsPlanAbsoluteDifference: -1911.77,
    currency: 'EUR',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2024110',
    brand: '2',
    country: 'DE',
    street: 'Salzstr. 47-50',
    zipCode: 'DE-48143',
    lastModifiedAt: '2024-07-31T12:40:57.263Z',
    lastModifiedBy: 'sonia.hutner@cecil.de',
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 5057.56,
    orderValueBudgetRelevant: 4114.32,
    orderValueOnTop: 5381.22,
    actualVsPreviousYearPercentage: -75.3084491335743,
    actualVsPreviousYearAbsoluteDifference: 0,
    menuSharePercentage: null,
    colorSharePercentage: 31.666666666666668,
    designDepartmentSharePercentage: 45.69222222222223,
    qrShare: 2399.64,
    qrSharePercentage: 78,
    rejectReason: null,
    campaignId: null,
    actions: ['VIEW', 'EXPORT', 'INSIGHTS', 'NEW_ORDER'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'carolin.alfs',
    posTypeValue: '02',
  },
  {
    customerNumber: '207084',
    customerId: 25376,
    customerName: 'Textilhäuser F. Klingenthal GmbH',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Berlin',
    parentCustomerNumber: '020758',
    orderId: 1104383,
    orderStatus: 'NOT_CREATED_YET',
    orderNumber: null,
    orderPieces: 186,
    salesPrice: 9916.14,
    planOrderValue: 4532.0,
    actualOrderValue: 4047.42,
    actualVsPlanPercentage: -10.692409532215352,
    actualVsPlanAbsoluteDifference: -484.5799999999999,
    currency: 'USD',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2024110',
    brand: '2',
    country: 'DE',
    street: 'Schloßstr. 7-10',
    zipCode: 'DE-12163',
    lastModifiedAt: '2024-07-31T12:41:19.263Z',
    lastModifiedBy: 'sonia.hutner@cecil.de',
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 2917.7200000000003,
    orderValueBudgetRelevant: 0.0,
    orderValueOnTop: 0.0,
    actualVsPreviousYearPercentage: 38.71858848690073,
    actualVsPreviousYearAbsoluteDifference: 1129.6999999999998,
    menuSharePercentage: null,
    colorSharePercentage: 100.0,
    designDepartmentSharePercentage: 85.0,
    qrShare: 5898.96,
    qrSharePercentage: 59,
    rejectReason: null,
    campaignId: null,
    actions: ['VIEW', 'EXPORT', 'INSIGHTS', 'NEW_ORDER'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'carolin.alfs',
    posTypeValue: '02',
  },
  {
    customerNumber: '207716',
    customerId: 25377,
    customerName: 'GALERIA S.à r.l. & Co. KG',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Nürnberg',
    parentCustomerNumber: '020758',
    orderId: 1103175,
    orderStatus: 'NOT_CREATED_YET',
    orderNumber: null,
    orderPieces: 103,
    salesPrice: 6168.97,
    planOrderValue: 4396.56,
    actualOrderValue: 2517.99,
    actualVsPlanPercentage: -42.72817839401715,
    actualVsPlanAbsoluteDifference: -1878.5700000000006,
    currency: 'GBP',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2024110',
    brand: '2',
    country: 'DE',
    street: 'Königstr. 14',
    zipCode: 'DE-90402',
    lastModifiedAt: '2024-07-31T12:41:08.24Z',
    lastModifiedBy: 'sonia.hutner@cecil.de',
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 3935.5299999999997,
    orderValueBudgetRelevant: 4114.32,
    orderValueOnTop: 5381.22,
    actualVsPreviousYearPercentage: -36.01903682604376,
    actualVsPreviousYearAbsoluteDifference: -1417.54,
    menuSharePercentage: null,
    colorSharePercentage: 71.63684210526317,
    designDepartmentSharePercentage: 64.672,
    qrShare: 4249.37,
    qrSharePercentage: 68,
    rejectReason: null,
    campaignId: null,
    actions: ['START_QEM_ORDER'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'carolin.alfs',
    posTypeValue: '02',
  },
  {
    customerNumber: '207862',
    customerId: 25453,
    customerName: 'GALERIA S.à r.l. & Co. KG',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Bremen',
    parentCustomerNumber: '020758',
    orderId: 1104353,
    orderStatus: 'APPROVED',
    orderNumber: null,
    orderPieces: 128,
    salesPrice: 7236.72,
    planOrderValue: 5220.56,
    actualOrderValue: 2953.82,
    actualVsPlanPercentage: -43.419479902539194,
    actualVsPlanAbsoluteDifference: -2266.7400000000002,
    currency: 'GBP',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2024110',
    brand: '2',
    country: 'DE',
    street: 'Obernstr. 5-33',
    zipCode: 'DE-28195',
    lastModifiedAt: '2024-07-31T12:41:13.87Z',
    lastModifiedBy: 'sonia.hutner@cecil.de',
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 6871.76,
    orderValueBudgetRelevant: 4114.32,
    orderValueOnTop: 5381.219999999999,
    actualVsPreviousYearPercentage: -57.01508783775917,
    actualVsPreviousYearAbsoluteDifference: -3917.94,
    menuSharePercentage: null,
    colorSharePercentage: 73.4895238095238,
    designDepartmentSharePercentage: 75.0,
    qrShare: 4969.2,
    qrSharePercentage: 68,
    rejectReason: null,
    campaignId: null,
    actions: ['VIEW', 'EXPORT', 'INSIGHTS'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'carolin.alfs',
    posTypeValue: '02',
  },
  {
    customerNumber: '100217',
    customerId: 16921,
    customerName: 'F. W. Fehling',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Burgdorf',
    parentCustomerNumber: '022416',
    orderId: 1132433,
    orderStatus: 'OPEN',
    orderNumber: null,
    orderPieces: 0,
    salesPrice: 0.0,
    planOrderValue: null,
    actualOrderValue: 0.0,
    actualVsPlanPercentage: null,
    actualVsPlanAbsoluteDifference: null,
    currency: 'EUR',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2025010',
    brand: '1',
    country: 'DE',
    street: 'Marktstr. 56',
    zipCode: 'DE-31303',
    lastModifiedAt: '2024-09-13T14:25:26.86Z',
    lastModifiedBy: 'tim.dieckmann@de.street-one.com',
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 3322.15,
    orderValueBudgetRelevant: null,
    orderValueOnTop: null,
    actualVsPreviousYearPercentage: -100.0,
    actualVsPreviousYearAbsoluteDifference: 3322.15,
    menuSharePercentage: null,
    colorSharePercentage: 0.0,
    designDepartmentSharePercentage: 0.0,
    qrShare: 0.0,
    qrSharePercentage: 0,
    rejectReason: null,
    campaignId: null,
    actions: ['VIEW', 'INSIGHTS'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'OKEL',
    posTypeValue: '02',
  },
  {
    customerNumber: '100217',
    customerId: 16921,
    customerName: 'F. W. Fehling',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Burgdorf',
    parentCustomerNumber: '022416',
    orderId: 1132437,
    orderStatus: 'OPEN',
    orderNumber: null,
    orderPieces: 0,
    salesPrice: 0.0,
    planOrderValue: null,
    actualOrderValue: 0.0,
    actualVsPlanPercentage: null,
    actualVsPlanAbsoluteDifference: null,
    currency: 'USD',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2025010',
    brand: '1',
    country: 'DE',
    street: 'Marktstr. 56',
    zipCode: 'DE-31303',
    lastModifiedAt: '2024-09-13T14:26:53.6Z',
    lastModifiedBy: 'tim.dieckmann@de.street-one.com',
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 3322.15,
    orderValueBudgetRelevant: null,
    orderValueOnTop: null,
    actualVsPreviousYearPercentage: -100.0,
    actualVsPreviousYearAbsoluteDifference: -3322.15,
    menuSharePercentage: null,
    colorSharePercentage: 0.0,
    designDepartmentSharePercentage: 0.0,
    qrShare: 0.0,
    qrSharePercentage: 0,
    rejectReason: null,
    campaignId: null,
    actions: ['VIEW', 'INSIGHTS', 'SUBMIT'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'OKEL',
    posTypeValue: '02',
  },
  {
    customerNumber: '101140',
    customerId: 17050,
    customerName: 'F. Klingenthal GmbH',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Herford',
    parentCustomerNumber: '019966',
    orderId: null,
    orderStatus: 'NOT_CREATED_YET',
    orderNumber: null,
    orderPieces: 0,
    salesPrice: 0.0,
    planOrderValue: null,
    actualOrderValue: 0.0,
    actualVsPlanPercentage: null,
    actualVsPlanAbsoluteDifference: null,
    currency: 'GBP',
    orderType: 'EPROM_MENU_ORDER',
    collection: '2025010',
    brand: '1',
    country: 'DE',
    street: 'Gehrenberg 11',
    zipCode: 'DE-32052',
    lastModifiedAt: null,
    lastModifiedBy: null,
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 6024.4,
    orderValueBudgetRelevant: null,
    orderValueOnTop: null,
    actualVsPreviousYearPercentage: -100.0,
    actualVsPreviousYearAbsoluteDifference: -6024.4,
    menuSharePercentage: null,
    colorSharePercentage: null,
    designDepartmentSharePercentage: null,
    qrShare: null,
    qrSharePercentage: null,
    rejectReason: null,
    campaignId: null,
    actions: ['START_FREE_ORDER', 'START_QEM_ORDER', 'START_MENU_ORDER'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'maren.rehse',
    posTypeValue: '02',
  },
  {
    customerNumber: '101140',
    customerId: 17050,
    customerName: 'F. Klingenthal GmbH',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Herford',
    parentCustomerNumber: '019966',
    orderId: null,
    orderStatus: 'NOT_CREATED_YET',
    orderNumber: null,
    orderPieces: 0,
    salesPrice: 0.0,
    planOrderValue: null,
    actualOrderValue: 0.0,
    actualVsPlanPercentage: null,
    actualVsPlanAbsoluteDifference: null,
    currency: 'EUR',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2025010',
    brand: '1',
    country: 'DE',
    street: 'Gehrenberg 11',
    zipCode: 'DE-32052',
    lastModifiedAt: null,
    lastModifiedBy: null,
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 6024.4,
    orderValueBudgetRelevant: null,
    orderValueOnTop: null,
    actualVsPreviousYearPercentage: -100.0,
    actualVsPreviousYearAbsoluteDifference: -6024.4,
    menuSharePercentage: null,
    colorSharePercentage: null,
    designDepartmentSharePercentage: null,
    qrShare: null,
    qrSharePercentage: null,
    rejectReason: null,
    campaignId: 686,
    actions: ['START_QEM_ORDER'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'maren.rehse',
    posTypeValue: '02',
  },
  {
    customerNumber: '102901',
    customerId: 17139,
    customerName: 'F. Klingenthal GmbH',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Gütersloh',
    parentCustomerNumber: '019966',
    orderId: null,
    orderStatus: 'NOT_CREATED_YET',
    orderNumber: null,
    orderPieces: 0,
    salesPrice: 0.0,
    planOrderValue: null,
    actualOrderValue: 0.0,
    actualVsPlanPercentage: null,
    actualVsPlanAbsoluteDifference: null,
    currency: 'USD',
    orderType: 'EPROM_MENU_ORDER',
    collection: '2025010',
    brand: '1',
    country: 'DE',
    street: 'Kolbeplatz 1',
    zipCode: 'DE-33330',
    lastModifiedAt: null,
    lastModifiedBy: null,
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 2351.1,
    orderValueBudgetRelevant: null,
    orderValueOnTop: null,
    actualVsPreviousYearPercentage: -100.0,
    actualVsPreviousYearAbsoluteDifference: 2351.1,
    menuSharePercentage: null,
    colorSharePercentage: null,
    designDepartmentSharePercentage: null,
    qrShare: null,
    qrSharePercentage: null,
    rejectReason: null,
    campaignId: null,
    actions: ['START_FREE_ORDER', 'START_QEM_ORDER'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'maren.rehse',
    posTypeValue: '02',
  },
  {
    customerNumber: '102901',
    customerId: 17139,
    customerName: 'F. Klingenthal GmbH',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Gütersloh',
    parentCustomerNumber: '019966',
    orderId: null,
    orderStatus: 'NOT_CREATED_YET',
    orderNumber: null,
    orderPieces: 0,
    salesPrice: 0.0,
    planOrderValue: null,
    actualOrderValue: 0.0,
    actualVsPlanPercentage: null,
    actualVsPlanAbsoluteDifference: null,
    currency: 'EUR',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2025010',
    brand: '1',
    country: 'DE',
    street: 'Kolbeplatz 1',
    zipCode: 'DE-33330',
    lastModifiedAt: null,
    lastModifiedBy: null,
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 2351.1,
    orderValueBudgetRelevant: null,
    orderValueOnTop: null,
    actualVsPreviousYearPercentage: -100.0,
    actualVsPreviousYearAbsoluteDifference: 0,
    menuSharePercentage: null,
    colorSharePercentage: null,
    designDepartmentSharePercentage: null,
    qrShare: null,
    qrSharePercentage: null,
    rejectReason: null,
    campaignId: 686,
    actions: ['START_QEM_ORDER'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'maren.rehse',
    posTypeValue: '02',
  },
  {
    customerNumber: '103801',
    customerId: 17228,
    customerName: 'F. Klingenthal GmbH',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Paderborn',
    parentCustomerNumber: '019966',
    orderId: null,
    orderStatus: 'NOT_CREATED_YET',
    orderNumber: null,
    orderPieces: 0,
    salesPrice: 0.0,
    planOrderValue: null,
    actualOrderValue: 0.0,
    actualVsPlanPercentage: null,
    actualVsPlanAbsoluteDifference: null,
    currency: 'EUR',
    orderType: 'EPROM_MENU_ORDER',
    collection: '2025010',
    brand: '1',
    country: 'DE',
    street: 'Westernstr. 22-24',
    zipCode: 'DE-33098',
    lastModifiedAt: null,
    lastModifiedBy: null,
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 6024.25,
    orderValueBudgetRelevant: null,
    orderValueOnTop: null,
    actualVsPreviousYearPercentage: -100.0,
    actualVsPreviousYearAbsoluteDifference: -6024.25,
    menuSharePercentage: null,
    colorSharePercentage: null,
    designDepartmentSharePercentage: null,
    qrShare: null,
    qrSharePercentage: null,
    rejectReason: null,
    campaignId: null,
    actions: [],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'maren.rehse',
    posTypeValue: '02',
  },
  {
    customerNumber: '103801',
    customerId: 17228,
    customerName: 'F. Klingenthal GmbH',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Paderborn',
    parentCustomerNumber: '019966',
    orderId: null,
    orderStatus: 'NOT_CREATED_YET',
    orderNumber: null,
    orderPieces: 0,
    salesPrice: 0.0,
    planOrderValue: null,
    actualOrderValue: 0.0,
    actualVsPlanPercentage: null,
    actualVsPlanAbsoluteDifference: null,
    currency: 'EUR',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2025010',
    brand: '1',
    country: 'DE',
    street: 'Westernstr. 22-24',
    zipCode: 'DE-33098',
    lastModifiedAt: null,
    lastModifiedBy: null,
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 6024.25,
    orderValueBudgetRelevant: null,
    orderValueOnTop: null,
    actualVsPreviousYearPercentage: -100.0,
    actualVsPreviousYearAbsoluteDifference: -6024.25,
    menuSharePercentage: null,
    colorSharePercentage: null,
    designDepartmentSharePercentage: null,
    qrShare: null,
    qrSharePercentage: null,
    rejectReason: null,
    campaignId: 686,
    actions: ['START_QEM_ORDER'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'maren.rehse',
    posTypeValue: '02',
  },
  {
    customerNumber: '112303',
    customerId: 17895,
    customerName: 'F. Klingenthal GmbH Südpol',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Paderborn',
    parentCustomerNumber: '019966',
    orderId: null,
    orderStatus: 'NOT_CREATED_YET',
    orderNumber: null,
    orderPieces: 0,
    salesPrice: 0.0,
    planOrderValue: null,
    actualOrderValue: 0.0,
    actualVsPlanPercentage: null,
    actualVsPlanAbsoluteDifference: null,
    currency: 'EUR',
    orderType: 'EPROM_MENU_ORDER',
    collection: '2025010',
    brand: '1',
    country: 'DE',
    street: 'Pohlweg 110',
    zipCode: 'DE-33100',
    lastModifiedAt: null,
    lastModifiedBy: null,
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 7502.950000000001,
    orderValueBudgetRelevant: null,
    orderValueOnTop: null,
    actualVsPreviousYearPercentage: -100.0,
    actualVsPreviousYearAbsoluteDifference: -7502.950000000001,
    menuSharePercentage: null,
    colorSharePercentage: null,
    designDepartmentSharePercentage: null,
    qrShare: null,
    qrSharePercentage: null,
    rejectReason: null,
    campaignId: null,
    actions: [],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'maren.rehse',
    posTypeValue: '02',
  },
  {
    customerNumber: '112303',
    customerId: 17895,
    customerName: 'F. Klingenthal GmbH Südpol',
    posType: 'SIS',
    posTypeIdentifier: '02',
    city: 'Paderborn',
    parentCustomerNumber: '019966',
    orderId: null,
    orderStatus: 'NOT_CREATED_YET',
    orderNumber: null,
    orderPieces: 0,
    salesPrice: 0.0,
    planOrderValue: null,
    actualOrderValue: 0.0,
    actualVsPlanPercentage: null,
    actualVsPlanAbsoluteDifference: null,
    currency: 'USD',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2025010',
    brand: '1',
    country: 'DE',
    street: 'Pohlweg 110',
    zipCode: 'DE-33100',
    lastModifiedAt: null,
    lastModifiedBy: null,
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 7502.950000000001,
    orderValueBudgetRelevant: null,
    orderValueOnTop: null,
    actualVsPreviousYearPercentage: -100.0,
    actualVsPreviousYearAbsoluteDifference: -7502.950000000001,
    menuSharePercentage: null,
    colorSharePercentage: null,
    designDepartmentSharePercentage: null,
    qrShare: null,
    qrSharePercentage: null,
    rejectReason: null,
    campaignId: 686,
    actions: ['START_QEM_ORDER'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'maren.rehse',
    posTypeValue: '02',
  },
  {
    customerNumber: '152539',
    customerId: 625921252,
    customerName: 'Textilhäuser F. Klingenthal GmbH',
    posType: 'SP',
    posTypeIdentifier: '04',
    city: 'Salzkotten',
    parentCustomerNumber: '019966',
    orderId: null,
    orderStatus: 'NOT_CREATED_YET',
    orderNumber: null,
    orderPieces: 0,
    salesPrice: 0.0,
    planOrderValue: null,
    actualOrderValue: 0.0,
    actualVsPlanPercentage: null,
    actualVsPlanAbsoluteDifference: null,
    currency: 'GBP',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2025010',
    brand: '1',
    country: 'DE',
    street: 'Lange Straße 21',
    zipCode: 'DE-33154',
    lastModifiedAt: null,
    lastModifiedBy: null,
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 5049.299999999999,
    orderValueBudgetRelevant: null,
    orderValueOnTop: null,
    actualVsPreviousYearPercentage: -100.0,
    actualVsPreviousYearAbsoluteDifference: 5049.299999999999,
    menuSharePercentage: null,
    colorSharePercentage: null,
    designDepartmentSharePercentage: null,
    qrShare: null,
    qrSharePercentage: null,
    rejectReason: null,
    campaignId: 686,
    actions: ['START_QEM_ORDER'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'maren.rehse',
    posTypeValue: '04',
  },
  {
    customerNumber: '152539',
    customerId: 625921252,
    customerName: 'Textilhäuser F. Klingenthal GmbH',
    posType: 'SP',
    posTypeIdentifier: '04',
    city: 'Salzkotten',
    parentCustomerNumber: '019966',
    orderId: null,
    orderStatus: 'NOT_CREATED_YET',
    orderNumber: null,
    orderPieces: 0,
    salesPrice: 0.0,
    planOrderValue: null,
    actualOrderValue: 0.0,
    actualVsPlanPercentage: null,
    actualVsPlanAbsoluteDifference: null,
    currency: 'EUR',
    orderType: 'EPROM_FREE_ORDER',
    collection: '2025010',
    brand: '1',
    country: 'DE',
    street: 'Lange Straße 21',
    zipCode: 'DE-33154',
    lastModifiedAt: null,
    lastModifiedBy: null,
    orderPiecesPreviousYear: null,
    orderValuePreviousYear: 5049.299999999999,
    orderValueBudgetRelevant: null,
    orderValueOnTop: null,
    actualVsPreviousYearPercentage: -100.0,
    actualVsPreviousYearAbsoluteDifference: -5049.299999999999,
    menuSharePercentage: null,
    colorSharePercentage: null,
    designDepartmentSharePercentage: null,
    qrShare: null,
    qrSharePercentage: null,
    rejectReason: null,
    campaignId: null,
    actions: ['START_MENU_ORDER'],
    containsCancelledItems: false,
    recommendationId: null,
    districtManager: 'maren.rehse',
    posTypeValue: '04',
  },
];

@Injectable({
  providedIn: 'root',
})
export class MockDataService {
  getData() {
    return mockData;
  }
}
